
 

ota:
  safe_mode: true
  password: !secret ota_password
  on_state_change:
    then:
      - lambda: "App.feed_wdt();delay(1);"




captive_portal:



web_server:
  port: 80
  version: 2
  auth:
    username: !secret web_user
    password: !secret web_password
  js_include: "www.js"
  js_url: ""
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password

  reboot_timeout: !secret wifi_reboot_timeout
  fast_connect: false
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

 
#debug:
#-------打印log设置，注意实际输出端口为主板上面的log_tx，而不是刷机用到的tx-------
logger:
  level: DEBUG  #不同的log等级看到的信息详细程度不一样，信息量从少到多依次为NONE、ERROR、WARN、INFO、DEBUG、VERBOSE、VERY_VERBOSE
#  baud_rate: 0 #设置为0关闭通过UART的log输出
#通过TTL看log信息，取消注释下面这行，读取接口为RX1，具体见模组接口说明图
#  hardware_uart: UART1



time:
  - platform: sntp
    id: sntp_time
    servers:
      - 0.pool.ntp.org
      - ntp.aliyun.com
      - time.mytime.ort
